### ISSUE TITLE
Please add a license.

### ISSUE THREAD

**Issue by samuelh2005** [MasonGulu/remos#3]
Adding a license will control what people can legally do with your code. Currently we are not legally allowed to install your software, even though the code is public on GitHub it doesn't mean we can use it. (see more: https://choosealicense.com/no-permission/) Currently you are legally liable for any issues that occur, this may become an issue in the future if no license is applied.

To add a license create a file called `LICENSE` inside the root of this repository and paste the content of the license of your choice inside it (and modify placeholders if there are any). To choose a license visit https://choosealicense.com.

I recommend the MIT license.

**Comment by ShreksHellraiser** [comment]
I'll add a license, but I'm curious on why you can't legally install it. The source code is the only way to distribute software written in Lua. I get there's concerns over legality but this is code for a virtual computer environment and I'm not gonna be going after someone for just installing/using it.

**Comment by samuelh2005** [comment]
People may be legally allowed to use it (depends on their country), however they cannot be sure what they are allowed to do. For example if someone wanted to add another app to the home screen they would need to modify the `home_apps.table` file, since you are the copyright owner they would need to get permission from you to do so. Or you may add a license like the MIT which allows modifications like this to be made

**Comment by samuelh2005** [comment]
Also, thanks for adding the license - this issue can now be closed.
